# Generated by Django 3.2.19 on 2023-09-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrderGoodServiceBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('title', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SupplyOrderGood',
            fields=[
                ('supplyordergoodservicebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supply.supplyordergoodservicebase')),
                ('order_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.ordergood')),
            ],
            bases=('supply.supplyordergoodservicebase',),
        ),
    ]
