# Generated by Django 3.2.19 on 2023-09-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyordergoodservicebase',
            name='title_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='supplyordergoodservicebase',
            name='title_lt',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
